# Generated by Django 4.0.3 on 2022-11-29 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_alter_species_distribution_alter_species_food'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mistakereports',
            name='comment',
            field=models.TextField(blank=True),
        ),
    ]
