# Generated by Django 4.0.3 on 2022-11-29 14:27

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_alter_mistakereports_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='species',
            name='food',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), size=None, verbose_name='Pożywienie'),
        ),
    ]
