# Generated by Django 4.0.3 on 2022-11-29 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_alter_species_food'),
    ]

    operations = [
        migrations.AlterField(
            model_name='species',
            name='food',
            field=models.CharField(max_length=500, verbose_name='Pożywienie'),
        ),
    ]
