# Generated by Django 4.0.3 on 2023-01-09 13:51

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('backend', '0008_alter_species_food'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comments',
            new_name='Comment',
        ),
        migrations.RenameModel(
            old_name='MistakeReports',
            new_name='MistakeReport',
        ),
        migrations.RenameModel(
            old_name='UserLinks',
            new_name='UserLink',
        ),
    ]
