# Generated by Django 4.0.3 on 2023-02-14 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_alter_species_distribution_alter_species_food'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mistakereport',
            name='test',
        ),
    ]
