# Generated by Django 4.0.3 on 2023-04-11 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_remove_mistakereport_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlink',
            name='activation',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userlink',
            name='set_new_password',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
