# Generated by Django 4.0.3 on 2023-05-25 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0014_alter_species_distribution_alter_species_food'),
    ]

    operations = [
        migrations.AlterField(
            model_name='species',
            name='picky_eater',
            field=models.BooleanField(blank=True, verbose_name='Specjalista pokarmowy'),
        ),
        migrations.AlterField(
            model_name='species',
            name='reefsafe',
            field=models.BooleanField(blank=True, verbose_name='Bezpieczny dla rafy'),
        ),
    ]
