# Generated by Django 4.0.3 on 2023-05-25 21:13

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0015_alter_species_picky_eater_alter_species_reefsafe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(max_length=2500),
        ),
        migrations.AlterField(
            model_name='mistakereport',
            name='text',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='species',
            name='distribution',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), size=None, verbose_name='Występowanie'),
        ),
        migrations.AlterField(
            model_name='species',
            name='food',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), size=None, verbose_name='Pożywienie'),
        ),
        migrations.AlterField(
            model_name='species',
            name='picky_eater',
            field=models.BooleanField(blank=True, null=True, verbose_name='Specjalista pokarmowy'),
        ),
        migrations.AlterField(
            model_name='species',
            name='reefsafe',
            field=models.BooleanField(blank=True, null=True, verbose_name='Bezpieczny dla rafy'),
        ),
    ]
